### PR TITLE
recompile c_comparing_distributions.pdf

### PR DESCRIPTION
**Pull request by mpadge**
Have a look at the [bottom of p2 on current version](https://github.com/csgillespie/poweRlaw/blob/master/pkg/inst/doc/c_comparing_distributions.pdf) under "one or two-sided *p*-value" - also unfortunately made it through [on CRAN](https://cran.r-project.org/web/packages/poweRlaw/vignettes/c_comparing_distributions.pdf). It just needed to be recompiled, which begs the question that i'd be interesting in you answering: Why do you include the compiled `pdf`s in your git and presumably your R build absent an `.Rbuildignore`? I'm purely interested in knowing your take on perceived advantages.

The other change just removes an extra `@export`,

A final comment: Great package, and if I may introduce myself, Hi Colin, I'm Mark, currently working on a manuscript which utilises [this package](https://github.com/mpadge/paretoconv) for the convolution of Pareto distributions extending from your package and the work of Clauset & co. I'll be in touch with you via other means soon (potential Christmas interruptions notwithstanding) to pursue discussion on potential co-authorship, merging of packages, and other topics-not-quite-yet-ripe-for-discussion, and will look forward to further exchanges ...

### CODE REVIEW

**Comment by mpadge** [comment]
A bit of extra motivation: This is what `paretoconv` does for the native American casualty data used in your JSS paper:
readme-gillespie-plot2-1
The model requires just one additional degree of freedom, and is valid for all `x>0`, rather than just `x>x0`. It's also obviously strongly favoured over single power-laws in all AIC-likelihood-whatever tests of performance-vs-complexity. The manuscript explains why ...

**Comment by csgillespie** [comment]
Thanks for PR.  

 * Regarding the `inst/doc` this is a throw back to an old version of the package when building the vignette took a while. After your comment I'm looking to remove the directory.

 * Looking forward to seeing you manuscript (feel free to email it to me).

Thanks

**Comment by csgillespie** [comment]
Now remembered why I had inst/doc. In the first version of the package, I had a fancy vignette that didn't build on CRAN. Adding the pdf to inst/doc got round this issue.

**Comment by mpadge** [comment]
@csgillespie just a heads up that i've emailed you a copy of the manuscript (to ncl), in case your junk filter caught it

**Pull request merged**
